= Ottawa-Gatineau Radio411
:showtitle:

The nation's capital is rife with RF of all sorts, and I thought it would be a fun project to create a central collaborative repository for everything radio-related within 100 kilometres of Parliament Hill. My goal is for this to not only be a list of active frequencies, but also a list of local resources for the radio hobbyist.

_La région de la capitale nationale est pleine de RF de toute sorte, et je me suis dis que ce serait un petit projet amusant de créer un dépot collaboratif pour tout ce qui est relié à la radio dans un rayon de 100 kilomètres de la colline du parlement. Mon but est que ceci ne soit pas simplement une liste de fréquences actives, mais aussi une liste de ressources locales pour les amateurs de radio	._
    	      
== How to collaborate - Comment collaborer

. *Git/Github*
+
The traditional way to do things, just like you would for any other software project. If you're familiar already with how Git/Github work, this should be easy. The project is written in asciidoc.
+
_La manière traditionelle de faire les chose, comme vous feriez pour n'importe quel autre project de logiciel. Si vous êtes déjà familier avec la manière dont fonctionne Git/Github, Le project est écrit en asciidoc._

. *Issues*
+
If you don't like asciidoc, aren't familiar with Git workflow, or simply don't feel like forking the repository and submitting a pull request, you can raise an issue in the repository containing the information you want to submit and I can add it in.
+
_Si vous n'aimez pas le asciidoc, n'êtes pas familier avec Git, ou ne voulez simplement pas télécharger le référentiel de code et soumettre une demande de tirage, vous pouvez soulever un problème dans le dépot contenant l'information que vous voulez soumettre et je pourrai l'ajouter._

. *Email / Courriel*
+
Finally, if you don't want to use Git/Github at all, just send an email to va2bbw@gmail.com with the frequency information and I can add it in.
+
_Finalement, si vous ne voulez pas utiliser Git/Github du tout, envoyez-moi simplement un courriel à va2bbw@gmail.com avec les informations sur la fréquence et je pourrai l'ajouter._

== Frequency and Resource Criteria / Critères pour fréquences et ressources

The frequencies and resources must be active or available within 100 kilometres of Parliament Hill, and within Canada.

_Les fréquences et ressources doivent être actives ou disponibles dans un rayon de 100 kilomètres de la colline du parlement, et à l'intérieur du Canada._
    	  
== Structure

The project structure is pretty straightforward:

_La structure du project est assez évidente:_

- The project's root directory contains all of the asciidoc files that hold the frequency and resource information.
+
_Le répertoire racine du projet contient tous les fichiers asciidoc où se trouve l'information sur les fréquences et les ressources._

- The "scripts" directory contains scripts to convert the asciidoc to other formats, like html, as well as other scripts used to build some of the lists.
+
_Le répertoire « scripts » contient des scripts pour convertir l'asciidoc en d'autres formats, comme le html, ainsi que d'autres scripts utilisés dans la création des listes._

- The other directories like "hmtl", "pdf", etc, contain the files converted to those formats.
+
_Les autres répertoires tels que "html, "pdf", etc, contiennent les fichiers convertis á ces formats._

== Frequencies / Fréquences

- xref:6m-Amateur-Analog.adoc[6m Amateur Radio Analog / Radio amateur 6m analogique]

'''

- xref:2m-Amateur-Analog.adoc[2m Amateur Radio Analog / Radio amateur 2m analogique]
- xref:2m-Amateur-Digital.adoc[2m Amateur Radio Digital / Radio amateur 2m numérique]

'''

- xref:135cm-Amateur-Analog.adoc[135cm Amateur Radio Analog / Radio amateur 135cm analogique]

'''

- xref:70cm-Amateur-Analog.adoc[70cm Amateur Radio Analog / Radio amateur 70cm analogique]
- xref:70cm-Amateur-Digital.adoc[70cm Amateur Radio Digital / Radio amateur 70cm numérique]

'''

- xref:frs-gmrs.adoc[FRS-GMRS]

'''

- xref:commercial-am.adoc[Commercial AM Radio / Radio commerciale AM]

'''

- xref:airband.adoc[Airband / Bande aviation]

== Resources / Ressources
- xref:ised-ham-db.adoc[ISED Amateur Database / Base de données amateur ISDE]
- xref:ised-accred-examiners.adoc[ISED Accredited Examiners / Examinateurs accrédités ISDE]
- xref:pota-parks.adoc[POTA Parks / Parcs POTA]
- xref:sota-summits.adoc[SOTA Summits / Sommets SOTA]
- xref:wwff-parks.adoc[WWFF Parks / Parcs WWFF]
- xref:arlhs-lighthouses.adoc[ARLHS Lighthouses / Phares ARLHS]
