= Ottawa-Gatineau Frequency List - Liste de fréquences Ottawa-Gatineau

The nation's capital is rife with RF of all sorts, and I thought it would be a fun little project and great resource to have a collaborative list of interesting frequencies. From amateur radio to commercial radio, from VHF/UHF and up down to LF, lets share what we have programmed in our scanners and transceivers from around the region.

_La région de la capitale nationale est pleine de RF de toute sorte, et je me suis dis que ce serait un petit projet amusant et une superbe ressource d'avoir une liste collaborative de fréquences intérèssantes. De la radio amateur à la radio commerciale, des fréquences VHF/UHF et au dessus aux fréquences LF, partageons ce que nous avons de programmé dans nos scanners et nos émetteurs-récepteurs de la région._

== How to collaborate - Comment collaborer

=== 1. Git/Github

The traditional way to do things, just like you would for any other software project. If you're familiar already with how Git/Github work, this should be easy. The main frequency lists are written in asciidoc and are converted into CSV, ODF, and other formats.

_La manière traditionelle de faire les chose, comme vous feriez pour n'importe quel autre project de logiciel. Si vous êtes déjà familier avec la manière dont fonctionne Git/Github, Les listes de fréquences principales sont rédigées en asciidoc et sont ensuite converties en CSV, ODF, et autres formats._

=== 2. Github Issues

If you don't like asciidoc, aren't familiar with Git workflow, or simply don't feel like forking the repository and submitting a pull request, you can raise an issue in the repository containing the information you want to submit and I can add it in.

_Si vous n'aimez pas le asciidoc, n'êtes pas familier avec Git, ou ne voulez simplement pas télécharger le référentiel de code et soumettre une demande de tirage, vous pouvez soulever un problème dans le dépot contenant l'information que vous voulez soumettre et je pourrai l'ajouter._

=== 3. Email - Courriel

Finally, if you don't want to use Git/Github at all, just send an email to va2bbw@gmail.com with the frequency information and I can add it in.

_Finalement, si vous ne voulez pas utiliser Git/Github du tout, envoyez-moi simplement un courriel à va2bbw@gmail.com avec les informations sur la fréquence et je pourrai l'ajouter._

== Frequencies/Fréquences

include::2m-Amateur-Analog.adoc[]
