= Ottawa-Gatineau Frequency List - Liste de fréquences Ottawa-Gatineau

The nation's capital is rife with RF of all sorts, and I thought it would be a fun little project and great resource to have a collaborative list of interesting frequencies. From amateur radio to commercial radio, from VHF/UHF and up down to LF, lets share what we have programmed in our scanners and transceivers from around the region.

_La région de la capitale nationale est pleine de RF de toute sorte, et je me suis dis que ce serait un petit projet amusant et une superbe ressource d'avoir une liste collaborative de fréquences intérèssantes. De la radio amateur à la radio commerciale, des fréquences VHF/UHF et au dessus aux fréquences LF, partageons ce que nous avons de programmé dans nos scanners et nos émetteurs-récepteurs de la région._

== How to collaborate - Comment collaborer

. *Git/Github*
+
The traditional way to do things, just like you would for any other software project. If you're familiar already with how Git/Github work, this should be easy. The project is written in asciidoc.
+
_La manière traditionelle de faire les chose, comme vous feriez pour n'importe quel autre project de logiciel. Si vous êtes déjà familier avec la manière dont fonctionne Git/Github, Le project est écrit en asciidoc._

. *Issues*
+
If you don't like asciidoc, aren't familiar with Git workflow, or simply don't feel like forking the repository and submitting a pull request, you can raise an issue in the repository containing the information you want to submit and I can add it in.
+
_Si vous n'aimez pas le asciidoc, n'êtes pas familier avec Git, ou ne voulez simplement pas télécharger le référentiel de code et soumettre une demande de tirage, vous pouvez soulever un problème dans le dépot contenant l'information que vous voulez soumettre et je pourrai l'ajouter._

. *Email / Courriel*
+
Finally, if you don't want to use Git/Github at all, just send an email to va2bbw@gmail.com with the frequency information and I can add it in.
+
_Finalement, si vous ne voulez pas utiliser Git/Github du tout, envoyez-moi simplement un courriel à va2bbw@gmail.com avec les informations sur la fréquence et je pourrai l'ajouter._
	     
== Frequency criteria / Critères pour fréquence

If it's an active frequency with transmissions that can be heard in and around the Ottawa-Gatineau area without requiring a multi-element yagi or other high-gain antenna, it can be included in this list. The goal is that anyone in the area with modest equipment has a reasonable chance of hearing things on these frequencies or making contact with other individuals on these frequencies.

_Si c'est une fréquence active avec des transmissions qui peuvent être entendues dans la région d'Ottawa-Gatineau sans nécéssiter l'utilisation d'une yagi multi-éléments ou autre antenne à haut gain, elle peut être incluse dans cette list. Le but est que n'importe qui dans la région avec de l'équipement modeste ait une chance raisonable d'entendre des choses sur ces fréquences ou d'établir des contacts avec d'autres individus sur ces fréquences._
    	  
== Frequencies / Fréquences
=== Amateur Radio / Radio amateur

- xref:2m-Amateur-Analog.adoc[2m Amateur Radio Analog / Radio amateur 2m analogique]
- xref:2m-Amateur-Digital.adoc[2m Amateur Radio Digital / Radio amateur 2m numérique]

//-

- xref:70cm-Amateur-Analog.adoc[70cm Amateur Radio Analog / Radio amateur 70cm analogique]
- xref:70cm-Amateur-Digital.adoc[70cm Amateur Radio Digital / Radio amateur 70cm numérique]

=== FRS / GMRS / CB

- xref:frs-gmrs.adoc[FRS]

=== Commercial FM Radio / Radio FM commerciale

=== Commercial AM Radio / Radio AM commerciale
=== Airband / Bande aviation   
=== Emergency Services / Services d'urgence

=== Municipal services / Services municipaux

=== Public transit, taxis, etc. / Transport en commun, taxis, etc.

=== Security Services / Services de sécurité
=== Government / Gouvernement
